name: APG
favicon: null
layout_spectrum: 0.49936600704677403
typography_spectrum: 0.01432664436288178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6760210879147053
  lightness: 0.7371354021597654
  saturation: 0.6111574966926128
  rhythmicContrast: 0.6584653053432703
purpose: []
